// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1QeJuZuoqAgTJZN_COnSiyCm9OEY7vE',
    appId: '1:342822097767:web:956966082e8f46f01f95c2',
    messagingSenderId: '342822097767',
    projectId: 'roomie-589a9',
    authDomain: 'roomie-589a9.firebaseapp.com',
    storageBucket: 'roomie-589a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6QgYJjsV1ku7-f_X1BWMxolvPtihs1AU',
    appId: '1:342822097767:android:cdc843375dda89f41f95c2',
    messagingSenderId: '342822097767',
    projectId: 'roomie-589a9',
    storageBucket: 'roomie-589a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcBvuJSFm3w8MPMCf29zHGI_rM8UyGjPA',
    appId: '1:342822097767:ios:e0fbf8a72109ccbe1f95c2',
    messagingSenderId: '342822097767',
    projectId: 'roomie-589a9',
    storageBucket: 'roomie-589a9.appspot.com',
    iosClientId: '342822097767-4oqcdqv3lu9v6lrbtptaunjictp8qis7.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomie',
  );
}
